### DISCUSSION TITLE
0 Packets on Goesrecv

### DISCUSSION THREAD

**Discussion by RHOD57** [JVital2013/goestools-win#4] [Troubleshooting] [answered]
Hi Jamie. Thanks for replying to me on YTube. Just tried 105 after doing a repair on C++. I'm using Win10. i5 laptop, Nooelec dish and Sawbird, and an newer RTL-SDR v3. SatDump works, but I'd really like to use GoesTools and Sanchez, but am trying to hold off on getting a Raspberry Pi. Any suggestions are appreciated. Thanks again.

![GOESWIN](https://github.com/JVital2013/goestools-win/assets/140870083/7beef86b-ce7d-41e4-bc0e-69f3b731718e)

**Comment by JVital2013** [comment]
Looks like the SDR is getting no signal.

How are you powering the SawBird? If you're using Bias-T power from the RTL-SDR, you need to activate the Bias-T in goesrecv. Open the `config\goesrecv-rtlsdr.conf` file and edit the `[rtlsdr]` section so it looks like this:

```toml
[rtlsdr]
frequency = 1694100000
sample_rate = 2400000
gain = 5
bias_tee = true
```

Then try again

**Reply by RHOD57** [reply]
I actually already found that line and added it. As far as I can tell, the hardware is good. I'm outside right now running SatDump.

![Screenshot 2023-07-29 092142](https://github.com/JVital2013/goestools-win/assets/140870083/4719f5cc-98d1-4017-b860-f4ca9453ba96)

I've spent some time tweaking the sample rate and gain in the config file. Still can't get more than an occasional few packets in the first iteration. I also have tried two different older RTL-SDR dongles, and two older laptops running Win10. Could it be the SNR is only at 6?  Hope that info helps, and thanks again.

**Reply by JVital2013** [reply]
Yep, looks like the hardware is good. A SNR of 6 in SatDump is pretty good for GOES! I rock around a 5.5 in SatDump. The issue is clearly not hardware.

Let's tick all the boxes at once:
- **Double-check you downloaded the GOES version of goestools-win**, not the one with gk2a in the name. The GK-2A version will not work for you
- **Double-check that your Visual C++ Redistributable is up-to-date**. Even if you think it is, download the latest version from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist and reinstall it.
- **Please share your entire goesrecv-rtlsdr.conf file** - I have a hunch the problem is in there.

Normally I'd say check that you have the correct RTL-SDR driver - but since it's working in SatDump, you almost certainly have the right one.

**Reply by RHOD57** [reply]
I'm using the https://aka.ms/vs/17/release/vc_redist.x64.exe version. I'll try a uninstall/reinstall. I've got the correct version of goestools-win also. Here's the config file.

```toml
# Change rtlsdr to airspy if you're using an AirSpy, etc.
[demodulator]
mode = "hrit"
source = "rtlsdr" 

# Change rtlsdr to airspy if you're using an AirSpy, etc.
# Other settings may vary based on your setup
[rtlsdr]
frequency = 1694100000
sample_rate = 2400000
gain = 5
bias_tee = true

# Change rtlsdr to airspy if you're using an AirSpy, etc.
# Publishes IQ samples coming straight from the SDR over
# nanomsg
[rtlsdr.sample_publisher]
bind = "tcp://0.0.0.0:5000"
send_buffer = 2097152

[costas]
max_deviation = 200e3

# Used by goesrecv-monitor to render constellation diagram
[clock_recovery.sample_publisher]
bind = "tcp://0.0.0.0:5002"
send_buffer = 2097152

# Used to pass data to goesproc, goeslrit, etc
[decoder.packet_publisher]
bind = "tcp://0.0.0.0:5004"
send_buffer = 1048576

# Used by goesrecv-monitor for statistics
[demodulator.stats_publisher]
bind = "tcp://0.0.0.0:6001"

# Used by goesrecv-monitor for statistics
[decoder.stats_publisher]
bind = "tcp://0.0.0.0:6002"

# Used by graphite/statsd
#[monitor]
statsd_address = "udp4://localhost:8125"
```

Sorry to be a PITA with this.
